version: '3'
services: 
  app:
    container_name: app
    build:
      context: ../app
      dockerfile: Dockerfile
    volumes:
      - ../app/src/:/home/node/app/src
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
  api:
    container_name: api
    build:
      context: ../api
      dockerfile: Dockerfile
    volumes:
      - ../api/src/:/home/node/api/src
    depends_on:
      - db  
    environment:
        WAIT_HOSTS: db:8443
    ports:
        - 8080:8080
  db:
    container_name: db
    image: fauna/faunadb:latest
    volumes:
      - dbdata:/var/log/faunadb
    restart: always
    ports:
      - 8443:8443
  db_shell:
    container_name: db_shell
    build:
      context: ../db
      dockerfile: Dockerfile
    restart: always
volumes:
  dbdata:

